server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL # MariaDB와 SQL 문법이 같음
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enable: true
  jpa:
    openInView: false
    hibernate:
      ddl-auto: create
    properties:
      '[hibernate.default_batch_fetch_size]': 100
      '[hibernate.format_sql]': true
    showSql: true
  output:
    ansi:
      enabled: always

logging:
  level:
    '[shop.mtcoding.bank]': DEBUG